spring:
  datasource:
    url: jdbc:mysql://106.75.141.99/micro-service?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 200428
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    connect-timeout: 300

jjwt:
  security:
    base64-secret: MDk5ZmU2YzdhZWE5NWRhZTU0MjgzMTVmMTkxYTI5ZGJmODc3NWU2ZDc5OWI1YWMxZTE5NWYxZWVhY2VmZGYwMWQ1NmExNjI4M2M2OWUzOGM0Nzg1ZGU2YzgxNWVjYzNhODg4YzE0ODhlZDA0YjZlYTgzYzk3MGE4NWFkMmJmOGI=
    token-validity-in-seconds: 300
    token-validity-in-seconds-for-remember-me: 2592000

